### ISSUE TITLE
get_nexrad_keys, "V06" tag

### ISSUE THREAD

**Issue by mathewbarlow** [openradar/TINT#38]
Hi, thanks for this excellent package!

The get_nexrad_keys function doesn't seem to handle the earlier data that doesn't have the "V06" tag in the filenames.

**Comment by zssherman** [comment]
Hi @mathewbarlow, thanks for bringing this up! I'll take a look and see if I can find a work around for earlier data.

**Comment by zssherman** [comment]
@mathewbarlow Do you know a datetime range where there would be data not under v06? Doing some testing.

**Comment by mathewbarlow** [comment]
Not sure when the change-over occurs, but I was seeing it for KBOX for 12/24/1999.  -Matt

Mathew Barlow

Professor of Climate Science
Department of Environmental, Earth, and Atmospheric Sciences
University of Massachusetts Lowell
Mathew_Barlow@uml.edu<mailto:Mathew_Barlow@uml.edu>





On May 26, 2020, at 4:33 PM, Zach Sherman <notifications@github.com<mailto:notifications@github.com>> wrote:

This e-mail originated from outside the UMass Lowell network.
________________________________


@mathewbarlow<https://urldefense.com/v3/__https://github.com/mathewbarlow__;!!PVKG_VDCxu5g!8tOBpVSRZJpedyF_dLFlc6N4EVI6WaWMLhC28x6ZJFt5yjSjkrePxfix8l6dmts1-M_m$> Do you know a datetime range where there would be data not under v06? Doing some testing.

**Comment by zssherman** [comment]
Perfect, much appreciated!

**Comment by zssherman** [comment]
Did a PR that should hopefully allow this now. I'll leave this issue open in the mean time.

**Comment by mathewbarlow** [comment]
Thanks!  -Matt

Mathew Barlow

Professor of Climate Science
Department of Environmental, Earth, and Atmospheric Sciences
University of Massachusetts Lowell
Mathew_Barlow@uml.edu<mailto:Mathew_Barlow@uml.edu>





On May 26, 2020, at 5:02 PM, Zach Sherman <notifications@github.com<mailto:notifications@github.com>> wrote:

This e-mail originated from outside the UMass Lowell network.
________________________________


Did a PR that should hopefully allow this now. I'll leave this issue open in the mean time.
