### ISSUE TITLE
Add instructions for citing

### ISSUE THREAD

**Issue by pedroaugustosmribeiro** [openradar/TINT#42]
Please add some instructions for citing this package.
You may consider issuing a DOI:
[https://guides.github.com/activities/citable-code/](url)

Thank you for this very handy code.

**Comment by zssherman** [comment]
Hi @pedroaugustosmribeiro at the moment:
https://www.atmos-meas-tech.net/12/2979/2019/
Should be used to cite. I'll do a PR for the README with this info. I think eventually this will change.

**Comment by zssherman** [comment]
Fridlind, A. M., van Lier-Walqui, M., Collis, S., Giangrande, S. E., Jackson, R. C., Li, X., Matsui, T., Orville, R., Picel, M. H., Rosenfeld, D., Ryzhkov, A., Weitz, R., and Zhang, P.: Use of polarimetric radar measurements to constrain simulated convective cell evolution: a pilot study with Lagrangian tracking, Atmos. Meas. Tech., 12, 2979–3000, https://doi.org/10.5194/amt-12-2979-2019, 2019.

**Comment by pedroaugustosmribeiro** [comment]
> Fridlind, A. M., van Lier-Walqui, M., Collis, S., Giangrande, S. E., Jackson, R. C., Li, X., Matsui, T., Orville, R., Picel, M. H., Rosenfeld, D., Ryzhkov, A., Weitz, R., and Zhang, P.: Use of polarimetric radar measurements to constrain simulated convective cell evolution: a pilot study with Lagrangian tracking, Atmos. Meas. Tech., 12, 2979–3000, https://doi.org/10.5194/amt-12-2979-2019, 2019.

Thank you very much @zssherman 
That's the paper I was already citing, its been very useful for my work, as is TINT.
